"""add_deleted_at_to_announcement

Revision ID: 95776c9b4c53
Revises: f8b583c69ec0
Create Date: 2026-05-19 09:51:00.749224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95776c9b4c53'
down_revision: Union[str, None] = 'f8b583c69ec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sch_announcement', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='永久隐藏时间（软删除标记）'))
    op.alter_column('sch_announcement', 'id',
               existing_type=sa.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sch_announcement', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否有效（False=已撤回）',
               existing_comment='是否有效',
               existing_nullable=False)
    op.alter_column('sch_message', 'id',
               existing_type=sa.INTEGER(),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sch_message', 'read_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_comment='阅读时间',
               existing_nullable=True)
    op.alter_column('sch_message', 'is_broadcast',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_comment='是否广播消息')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sch_message', 'is_broadcast',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_comment='是否广播消息')
    op.alter_column('sch_message', 'read_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_comment='阅读时间',
               existing_nullable=True)
    op.alter_column('sch_message', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('sch_announcement', 'is_active',
               existing_type=sa.BOOLEAN(),
               comment='是否有效',
               existing_comment='是否有效（False=已撤回）',
               existing_nullable=False)
    op.alter_column('sch_announcement', 'id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('sch_announcement', 'deleted_at')
    # ### end Alembic commands ###
