"""add_deleted_at_to_message

Revision ID: bf59a454f2b3
Revises: 95776c9b4c53
Create Date: 2026-05-19 10:03:30.560483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf59a454f2b3'
down_revision: Union[str, None] = '95776c9b4c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sch_message', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='永久隐藏时间（软删除标记）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sch_message', 'deleted_at')
    # ### end Alembic commands ###
