"""add_message_and_announcement_tables

Revision ID: f8b583c69ec0
Revises: f9f493e67b81
Create Date: 2026-05-18 22:24:09.805728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8b583c69ec0'
down_revision: Union[str, None] = 'f9f493e67b81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sch_announcement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False, comment='公告标题'),
    sa.Column('content', sa.Text(), nullable=False, comment='公告内容'),
    sa.Column('publisher_id', sa.Integer(), nullable=False, comment='发布人'),
    sa.Column('target_scope', sa.String(length=20), nullable=False, comment='目标范围：all/org/role'),
    sa.Column('target_ids', sa.String(length=500), nullable=True, comment='目标ID列表（JSON字符串）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否有效'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['publisher_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='公告表'
    )
    op.create_table('sch_message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False, comment='接收人'),
    sa.Column('sender_id', sa.Integer(), nullable=True, comment='发送人（系统消息为空）'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='消息标题'),
    sa.Column('content', sa.Text(), nullable=True, comment='消息内容'),
    sa.Column('msg_type', sa.String(length=20), nullable=False, comment='消息类型：schedule/swap/approve/system'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='是否已读'),
    sa.Column('read_time', sa.DateTime(), nullable=True, comment='阅读时间'),
    sa.Column('relation_type', sa.String(length=30), nullable=True, comment='关联类型：schedule/swap_request/announcement'),
    sa.Column('relation_id', sa.Integer(), nullable=True, comment='关联业务ID'),
    sa.Column('is_broadcast', sa.Boolean(), nullable=True, comment='是否广播消息'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['receiver_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='系统消息表'
    )
    op.create_index(op.f('ix_sch_message_is_read'), 'sch_message', ['is_read'], unique=False)
    op.create_index(op.f('ix_sch_message_receiver_id'), 'sch_message', ['receiver_id'], unique=False)
    op.create_index('ix_sch_message_receiver_read_time', 'sch_message', ['receiver_id', 'is_read', 'created_at'], unique=False)
    op.drop_index('ix_sys_message_is_read', table_name='sys_message')
    op.drop_index('ix_sys_message_msg_type', table_name='sys_message')
    op.drop_index('ix_sys_message_user_id', table_name='sys_message')
    op.drop_table('sys_message')
    op.alter_column('sch_shift_template', 'rotation_frequency',
               existing_type=sa.VARCHAR(length=20),
               comment='整体轮换频次：day/week/month',
               existing_nullable=False,
               existing_server_default=sa.text("'day'::character varying"))
    op.alter_column('sch_shift_template', 'schedule_mode',
               existing_type=sa.VARCHAR(length=20),
               comment='排班模式：individual/team_rotation/rotation_group',
               existing_nullable=False,
               existing_server_default=sa.text("'individual'::character varying"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sch_shift_template', 'schedule_mode',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='排班模式：individual/team_rotation/rotation_group',
               existing_nullable=False,
               existing_server_default=sa.text("'individual'::character varying"))
    op.alter_column('sch_shift_template', 'rotation_frequency',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='整体轮换频次：day/week/month',
               existing_nullable=False,
               existing_server_default=sa.text("'day'::character varying"))
    op.create_table('sys_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='接收人ID'),
    sa.Column('msg_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False, comment='消息类型 schedule/swap/approve/announcement'),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False, comment='消息标题'),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False, comment='消息内容'),
    sa.Column('related_type', sa.VARCHAR(length=30), autoincrement=False, nullable=True, comment='关联业务类型'),
    sa.Column('related_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='关联业务ID'),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='是否已读'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2026-05-16 01:22:17.58833+08'::timestamp with time zone"), autoincrement=False, nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['user_id'], ['sys_user.id'], name='sys_message_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sys_message_pkey')
    )
    op.create_index('ix_sys_message_user_id', 'sys_message', ['user_id'], unique=False)
    op.create_index('ix_sys_message_msg_type', 'sys_message', ['msg_type'], unique=False)
    op.create_index('ix_sys_message_is_read', 'sys_message', ['is_read'], unique=False)
    op.drop_index('ix_sch_message_receiver_read_time', table_name='sch_message')
    op.drop_index(op.f('ix_sch_message_receiver_id'), table_name='sch_message')
    op.drop_index(op.f('ix_sch_message_is_read'), table_name='sch_message')
    op.drop_table('sch_message')
    op.drop_table('sch_announcement')
    # ### end Alembic commands ###
