"""add_rotation_group_table

Revision ID: f9f493e67b81
Revises: ca4760dc63a1
Create Date: 2026-05-18 08:41:13.343015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9f493e67b81'
down_revision: Union[str, None] = 'ca4760dc63a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sch_rotation_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('shift_template_id', sa.Integer(), nullable=False, comment='所属班次模板ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='轮换组名称'),
    sa.Column('staff_ids', sa.Text(), nullable=False, comment='轮换人员ID列表JSON'),
    sa.Column('rotation_unit', sa.String(length=20), nullable=False, comment='轮换周期：day/week/month'),
    sa.Column('slot_count', sa.Integer(), nullable=False, comment='该组占位数'),
    sa.Column('priority', sa.Integer(), nullable=False, comment='优先级，数字越小越优先'),
    sa.Column('enabled', sa.Integer(), nullable=False, comment='是否启用 1=是 0=否'),
    sa.ForeignKeyConstraint(['shift_template_id'], ['sch_shift_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sch_rotation_group')
    # ### end Alembic commands ###
