#!/bin/bash
# ============================================
# deploy/lib/nginx_helper.sh — Nginx 配置管理
# ============================================

if ! declare -f log_info &>/dev/null; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source "$SCRIPT_DIR/common.sh"
fi

NGINX_SITES_AVAILABLE="/etc/nginx/sites-available"
NGINX_SITES_ENABLED="/etc/nginx/sites-enabled"
NGINX_CONF_NAME="sps-system"

# ---------- 生成 Nginx 站点配置 ----------
generate_nginx_config() {
    local app_dir="$1"
    local domain="${2:-localhost}"
    local frontend_dist="$app_dir/frontend/dist"
    local config_file="$NGINX_SITES_AVAILABLE/$NGINX_CONF_NAME"

    log_info "生成 Nginx 配置: $config_file"

    # 备份旧配置
    backup_file "$config_file"

    cat > "$config_file" << NGINX_EOF
# SPS System - Auto-generated by deploy.sh
# Do not edit manually

server {
    listen 80;
    server_name ${domain};

    # 前端静态文件
    location / {
        root ${frontend_dist};
        try_files \$uri \$uri/ /index.html;

        # 安全头
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
    }

    # 后端 API 代理
    location /api/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
    }

    # WebSocket 支持
    location /ws/ {
        proxy_pass http://127.0.0.1:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 86400s;
    }

    # 日志
    access_log /var/log/nginx/sps-system-access.log;
    error_log /var/log/nginx/sps-system-error.log;
}
NGINX_EOF

    log_success "Nginx 配置已生成: $config_file"
    return 0
}

# ---------- 启用 Nginx 站点 ----------
enable_nginx_site() {
    local config_file="$NGINX_SITES_AVAILABLE/$NGINX_CONF_NAME"
    local enabled_link="$NGINX_SITES_ENABLED/$NGINX_CONF_NAME"

    log_info "启用 Nginx 站点..."

    # 移除默认站点（如果存在且未修改过）
    if [[ -f "$NGINX_SITES_ENABLED/default" ]]; then
        local default_hash
        default_hash=$(md5sum "$NGINX_SITES_ENABLED/default" 2>/dev/null | awk '{print $1}')
        # 如果是系统默认的简单配置，移除它
        if [[ "$default_hash" == "e2a4a9e..."* || -L "$NGINX_SITES_ENABLED/default" ]]; then
            rm -f "$NGINX_SITES_ENABLED/default"
            log_debug "已移除默认站点"
        fi
    fi

    # 创建符号链接
    ln -sf "$config_file" "$enabled_link"
    log_debug "已创建软链接: $enabled_link -> $config_file"

    # 测试配置
    if ! nginx -t 2>&1; then
        log_error "Nginx 配置测试失败，已回滚"
        rm -f "$enabled_link"
        return 1
    fi

    # 重载 Nginx
    systemctl reload nginx 2>/dev/null || service nginx reload 2>/dev/null
    log_success "Nginx 站点已启用并重载"
    return 0
}

# ---------- 安装 Certbot ----------
install_certbot() {
    log_info "安装 Certbot (HTTPS)..."

    if check_command certbot; then
        log_debug "Certbot 已安装"
        return 0
    fi

    # Ubuntu/Debian
    if check_command apt; then
        sudo apt update
        sudo apt install -y certbot python3-certbot-nginx
        log_success "Certbot 安装完成"
    else
        log_error "无法自动安装 Certbot，请手动安装"
        return 1
    fi
}

# ---------- 配置 HTTPS ----------
setup_https() {
    local domain="$1"

    log_info "配置 HTTPS: $domain"

    install_certbot || return 1

    sudo certbot --nginx -d "$domain" --non-interactive --agree-tos -m "admin@${domain}"

    if [[ $? -eq 0 ]]; then
        log_success "HTTPS 配置完成"
    else
        log_error "HTTPS 配置失败"
        return 1
    fi
}
