#!/bin/bash
# ============================================
# deploy/lib/systemd_helper.sh — systemd 服务管理
# ============================================

if ! declare -f log_info &>/dev/null; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source "$SCRIPT_DIR/common.sh"
fi

SERVICE_NAME="sps-backend"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"
SERVICE_USER="sps"

# ---------- 创建应用用户 ----------
ensure_service_user() {
    log_info "确保服务用户 '$SERVICE_USER' 存在..."

    if id "$SERVICE_USER" &>/dev/null; then
        log_debug "用户 '$SERVICE_USER' 已存在"
        return 0
    fi

    sudo useradd --system --no-create-home --shell /usr/sbin/nologin "$SERVICE_USER" 2>/dev/null
    if [[ $? -eq 0 ]]; then
        log_success "服务用户 '$SERVICE_USER' 已创建"
    else
        log_warn "无法自动创建用户 '$SERVICE_USER'，请手动创建或使用 --force 跳过"
        log_warn "sudo useradd --system --no-create-home $SERVICE_USER"
    fi
}

# ---------- 生成 systemd 单元文件 ----------
generate_systemd_unit() {
    local app_dir="$1"
    local backend_dir="$app_dir/backend"
    local uvicorn_cmd="$backend_dir/venv/bin/uvicorn"
    local workers="${2:-4}"

    log_info "生成 systemd 单元文件: $SERVICE_FILE"

    ensure_service_user

    # 确保目录存在
    sudo mkdir -p "$(dirname "$SERVICE_FILE")"

    # 备份旧配置
    backup_file "$SERVICE_FILE"

    # 设置目录所有权
    sudo chown -R "$SERVICE_USER:$SERVICE_USER" "$backend_dir" 2>/dev/null || true
    sudo chmod -R 755 "$backend_dir" 2>/dev/null || true

    cat > "$SERVICE_FILE" << EOF
# SPS Backend Service - Auto-generated by deploy.sh
# Do not edit manually

[Unit]
Description=SPS Backend Service (排班管理系统后端)
After=network.target postgresql.service

[Service]
Type=simple
User=${SERVICE_USER}
Group=${SERVICE_USER}
WorkingDirectory=${backend_dir}
EnvironmentFile=${backend_dir}/.env

ExecStart=${uvicorn_cmd} app.main:app \
    --host 0.0.0.0 --port 8000 --workers ${workers}

Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal

# 资源限制
LimitNOFILE=65536
Nice=10

# 安全加固
ProtectSystem=strict
ReadWritePaths=${backend_dir}
PrivateTmp=true
NoNewPrivileges=true

[Install]
WantedBy=multi-user.target
EOF

    log_success "systemd 单元文件已生成: $SERVICE_FILE"
    return 0
}

# ---------- 启用并启动服务 ----------
enable_service() {
    log_info "重载 systemd 并启用服务 '$SERVICE_NAME'..."

    sudo systemctl daemon-reload
    sudo systemctl enable "$SERVICE_NAME"

    log_success "服务已启用，设置为开机自启"
}

# ---------- 重启服务 ----------
restart_service() {
    log_info "重启服务 '$SERVICE_NAME'..."

    sudo systemctl restart "$SERVICE_NAME"

    if [[ $? -eq 0 ]]; then
        log_success "服务重启成功"
        return 0
    else
        log_error "服务重启失败"
        return 1
    fi
}

# ---------- 获取服务状态 ----------
get_service_status() {
    systemctl status "$SERVICE_NAME" --no-pager 2>/dev/null
}

# ---------- 停止服务 ----------
stop_service() {
    log_info "停止服务 '$SERVICE_NAME'..."
    sudo systemctl stop "$SERVICE_NAME"
    log_success "服务已停止"
}
